Feat/#0109 edit partnership
The-Bugger-Ducks/owl-partners-mobile pull request #34
Opened 2023-04-04 03:21 UTC by JoaoM-py

Edição de parceria
---------

- Foram feitas tipagens de alguns campos do formulário para que o mesmo seja aceito ao enviar e receber;
- Padronização dos inputs conforme a criação de formulários ;
- Atualização de informação depois de editar;

https://user-images.githubusercontent.com/80930525/229678859-663b6e9a-c26f-4d1f-a245-08893acd984a.mp4

2023-04-05 16:43 UTC, ThHenrique requested changes
Boa jão, leva em consideração os comentários 🤝

2023-04-05 16:43 UTC, ThHenrique commented on package.json
> +    "react-native": "0.71.6",
hmmm pq essa mudança aqui ?

2023-04-05 16:43 UTC, ThHenrique commented on src/screens/Partnership/index.tsx
> +  //   >();
Remove os códigos comentados, não tem utilidade

2023-04-05 16:43 UTC, ThHenrique commented on src/screens/Partnership/index.tsx
> +    const { id } = route.params;
Já que utiliza esse id em mais de uma função poderia declarar ela em escopo geral (fora das funções específicas)

2023-04-05 16:43 UTC, ThHenrique commented on src/shared/services/api.ts
> +  console.log(token);
Remove o log

2023-04-05 20:03 UTC, JoaoM-py commented on package.json
> +    "react-native": "0.71.6",
acho que foi o expo

2023-04-05 20:19 UTC, MariaGabrielaReis commented on package.json
> +    "react-native": "0.71.6",
que não quebre meu ambiente aqui, mas vou confiar kkk

2023-04-05 20:21 UTC, MariaGabrielaReis commented on src/screens/Partnership/index.tsx
> +  async function getPartnerships() {
Não gosto da ideia de ser "getPartnerships" sendo que essa tela é de uma parceria específica, mas a gente muda isso nas refatorações dps, puro detalhe

2023-04-05 20:22 UTC, JoaoM-py commented on package.json
> +    "react-native": "0.71.6",
única coisa que eu lembro que pode ter alterado isso ai foi o expo doctor --fix-dependencies

2023-04-05 20:30 UTC, MariaGabrielaReis requested changes
Show de bola, xuxu. Só vou pedir que volte com o id de dependência no useEffect e chame a função que pega os dados da parceria depois de deletar que por mim belezura ✨

2023-04-05 20:30 UTC, MariaGabrielaReis commented on src/screens/Partnership/index.tsx
> -    getData();
Acho que pode voltar o "getData" daqui? (agora é "getPartnerships", eu chamava a função dps de deletar pq precisa atualizar a UI. Quando uma parceria é deletada, não pode mais aparecer os botões de ações e tem uma msg falando que ela tá desativada e pá)

2023-04-05 20:30 UTC, MariaGabrielaReis commented on src/screens/Partnership/index.tsx
> -  }, [partnershipId]);
eu deixei o id da parceria como dependência pro useEffect da listagem pq uma vez carregada a tela, ele não recarrega os componentes, então colocando que o refetch tem que ser feito sempre que mudar o id, ele sempre buscava de novo as anotações

2023-04-05 21:46 UTC, MariaGabrielaReis approved these changes

2023-04-06 01:37 UTC, ThHenrique approved these changes
meeec

2023-04-06 01:38 UTC, merged