Feature/#0110 search bar
The-Bugger-Ducks/owl-partners-mobile pull request #55
Opened 2023-04-23 00:59 UTC by drisabelles

## Documentação
#### Issue relacionada: #32 

Criação da barra de busca com a filtragem das parcerias.

Tecnologias: React Native, Expo, Axios, Styled Components

https://user-images.githubusercontent.com/79321198/233813710-0aee4ce6-08c0-4125-ab2f-3ce2b09f008c.mp4

Requisição para listar as parcerias por nome:
```ts
 async getPartnershipByName(name: string) {
    try {
      const { data } = await api.get(
        PARTNERSHIP_ENDPOINTS.LIST_BY_NAME + `?name=${name}`,
      );
      return data;
    } catch (error) {
      alertError(error, "Não foi possível filtrar as parcerias");
    }
  }
```

2023-04-23 01:23 UTC, MariaGabrielaReis requested changes
Goxtei, só esse detalhezinho do type no input como any que me deixou com uma pulguinha atrás da orelha sz

2023-04-23 01:23 UTC, MariaGabrielaReis commented on src/components/Input/index.tsx
> +  type?: any;
N sei se precisava desse type como any não hein xuxu

2023-04-23 01:23 UTC, MariaGabrielaReis commented on src/screens/Partnerships/index.tsx
> +          type="text"
Mesma coisa aqui, n sei se precisa deixar explícito que o type é text, acho que é o default sz

2023-04-23 21:56 UTC, ThHenrique requested changes
Muito bom!!! Algumas pequenas observações para corrigir apenas.

Outra coisa seria a implementação de um debounce, ou então um botão para realizar o filtro, pq da maneira implementada a cada caracter adicionado no input será feita uma requisição, ou seja, para uma pesquisa do nome ESCOLA, seriam feitas 6 requisições. Isso não é bom

2023-04-23 21:56 UTC, ThHenrique commented on src/screens/Partnerships/index.tsx
> +      tab === 1,
Acho que pra quem não sabe o que se trata essas tabs, fica complicado de entender, seria bom criar uma variável em cima que representasse o que esse tab === 1 esta fazendo. Algo como listPartnershipDisabled, ou algo melhor.

2023-04-23 21:56 UTC, ThHenrique commented on src/shared/constants/endpoints.ts
> +  LIST_BY_NAME = "/partners/search",
Não é necessário adicionar uma cópia de endpoint's. No arquivo de request está sendo usado o LIST, entao o LISTBYNAME não está sendo usado.

2023-04-24 00:25 UTC, JoaoM-py approved these changes

2023-04-24 00:27 UTC, ThHenrique commented on src/screens/Partnerships/index.tsx
> +    const isPartnershipDisabledTab = tab === 1;
Lindo

2023-04-24 00:28 UTC, ThHenrique approved these changes
Boa!!

2023-04-24 00:37 UTC, ThHenrique approved these changes

2023-04-24 00:39 UTC, MariaGabrielaReis approved these changes

2023-04-24 00:40 UTC, merged