Feat/#0409 permission management
The-Bugger-Ducks/owl-partners-mobile pull request #86
Opened 2023-06-02 00:40 UTC by JoaoM-py

<h1>Documentação</h1>

<h3>#69 Gerenciar permissões do usuário </h3>

- Permitir que usuário administrador possa alterar a permissão do usuário podendo rebaixá-lo ou promovê-lo:
   - Se o usuário for admin não é possível promover;
   - Se o usuário for simple não é possível rebaixar;
   
   
   

https://github.com/The-Bugger-Ducks/owl-partners-mobile/assets/80930525/2bfa636c-2607-4c45-b512-1a4d77132a4e

2023-06-02 21:07 UTC, MariaGabrielaReis requested changes
Muito bacano, só um detalhezinho ali na requisição e é caixa ✨ 

![para bens](https://i0.wp.com/omeudiadia.com.br/wp-content/uploads/2022/06/7d35511cb0318505988e2a5495f4409e.gif)

2023-06-02 21:07 UTC, MariaGabrielaReis commented on src/shared/services/user.request.ts
> +    const updateUserPermission = await api.put(
adiciona um `try catch` nessa requisição pufavorzinho? 😊

2023-06-03 04:28 UTC, ThHenrique requested changes
Muito bom jaun, adorei ver usando os Icones 🥉. Uma pequena mudança que solicitei apenas

2023-06-03 04:28 UTC, ThHenrique commented on src/screens/User/index.tsx
Na linha 138 no {user.role} adiciona uma tratativa para o nome das roles, no video aparece ADMIN e SIMPLE, acredito que seria Admin e Simples ou administrador e simples, nao sei

2023-06-03 12:39 UTC, MariaGabrielaReis commented on src/screens/User/index.tsx
Ao invés de "simples" pode ser "visitante" né? afinal ele só entra pra fazer leitura dos dados e tals

2023-06-04 02:42 UTC, ThHenrique approved these changes
Aprovado pai

2023-06-04 11:32 UTC, MariaGabrielaReis approved these changes
Showw

2023-06-04 11:52 UTC, merged