Feat/#83 0115 filtragem das parcerias por status
The-Bugger-Ducks/owl-partners-mobile pull request #87
Opened 2023-06-03 08:18 UTC by ThHenrique

<h1>Documentação</h1>

<h3>#83 Filtragem das parcerias por status </h3>
  

### Importante

refatorei esse método que estava dificil de ler e entender

```
async getPartnerships(disabled = false, name = "", status = "") {
    try {
      let url = PARTNERSHIP_ENDPOINTS.LIST + `?disabled=${disabled}`;

      if (name) {
        url += `&name=${name}`;
      }

      if (status) {
        url += `&status=${status}`;
      }

      const { data } = await api.get<IPartnership[]>(url);

      return formatPartnerStatusByList(data);
    } catch (error) {
      alertError(error, "Não foi possível carregar a lista de parcerias :(");
    }
  }

```
   
### Demonstração
https://github.com/The-Bugger-Ducks/owl-partners-mobile/assets/58437896/839fb3bb-8c9e-43a0-82e8-944dc3e3c73c

2023-06-03 12:25 UTC, MariaGabrielaReis requested changes
PR pra main não né, amigo kkk por favor trocar para p PR ir para dev 😄 

Achei que ficou usual o filtro, confesso que um modal com várias linhas de texto assim não ficou muito agradável visualmente, mas aquele checkzinho vermelho que vc coloca do lado quando tá filtrando ficou bom. Minha sugestão para melhorar o layout seria colocar o check na esquerda e deixar ele sempre visível, mas cinza, e quando ativo fica vermelho, aí parece uma lista clicável msm onde vc escolhe a opção e etc, mas é apenas uma sugestão, do jeito que está acredito que supre a task de filtragem.

Show de bola, Thiagão!

![para bens](https://usagif.com/wp-content/uploads/applause-36.gif)

2023-06-03 20:53 UTC, JoaoM-py requested changes
Achei bala, não liguei muito pro ícone só mudar o bagulho pra Dev mesmo

2023-06-03 20:55 UTC, JoaoM-py approved these changes

2023-06-04 03:33 UTC, ThHenrique commented
Concordo @MariaGabrielaReis nao ficou muito legal esse modal com as opcoes, eu tentei utilizar o picker customizando para utilizar o icone de filtro, mas o picker é como se fosse um input select então não consegui utilizar apenas o dropdown dele, ele adicionava o "input" com o valor selecionado. Enfim, eu gostei da sua sugestão e fiz alteração, melhorou muito. Obrigado

2023-06-04 11:33 UTC, MariaGabrielaReis approved these changes
Braboo 🤝

2023-06-04 13:01 UTC, merged